#!/usr/bin/env bash
if [ $(tmux ls 2>/dev/null | wc -l) -gt 0 ]; then
    exit 1
fi

tmux kill-server >/dev/null 2>&1
tmux new-session -d

while [ $(tmux ls 2>/dev/null | wc -l) -gt 0 ]; do
    sleep 60
done
