#!/usr/bin/env bash

# See http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/752

if [ $(tmux ls 2>/dev/null | wc -l) -gt 0 ]; then
    exit 1
fi

tmux kill-server >/dev/null 2>&1
tmux new-session -d

while [ $(tmux ls 2>/dev/null | wc -l) -gt 0 ]; do
    sleep 60
done
